### ISSUE TITLE
Encountering build errors. Are there any proper documents available?

### ISSUE THREAD

**Issue by sakthiskv** [Netflix/EVCache#146]
I just cloned the project and am trying to set it up locally. I’m encountering build errors, and resolving one error often leads to another. Is there a comprehensive document for setting up the project?

**1. Could not resolve all artifacts for configuration ':classpath'. > Could not find org.ajoberstar.grgit:grgit-core:4.0.2.
2. testTouch FAILED
    com.netflix.evcache.EVCacheException at EVCacheTestDI.java:106
3. What went wrong:
Error resolving plugin [id: 'com.github.hierynomus.license', version: '0.14.0']
> The request for this plugin could not be satisfied because the plugin is already on the classpath with an unknown version, so compatibility cannot be checked.
**

**Comment by kilink** [comment]
This should be fixed by #148.
