### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by pauloricardomg** [Netflix/EVCache#17]
The project hasn't seen any official updates for the past 10 months. Many announced features, such as the EVCache server and remote cache invalidation never made it to the open source branch. Any plans on supporting these features soon?

**Comment by smadappa** [comment]
For sidecar you can use Prana (https://github.com/Netflix/Prana) which was opensourced recently. You can bundle them together in an AMI. If you are using servo i can provide the groovy plugin which sends  server side metrics to it. Let me know if you need anything else.
