### ISSUE TITLE
How long before EvCache Server is open-sourced?

### ISSUE THREAD

**Issue by pparth** [Netflix/EVCache#2]

**Comment by mbrocious** [comment]
Still interested...any update?

**Comment by kukgini** [comment]
Still working on it?

**Comment by smadappa** [comment]
EVCache Server is AMI which includes stock memcached (http://www.memcached.org) + Prana (https://github.com/Netflix/Prana). If you are using servo for metric collection we can provide you with a plugin that allows publishing of metrics from EVCache Server to Servo. 

@senugula is working on documenting this process.

**Comment by senugula** [comment]
I will have this documented in next 2 weeks

**Comment by ADenisUA** [comment]
Could someone please point me to the source codes and documentation for EVCache Server ?
