### ISSUE TITLE
EVCacheClient doesn't provide incr/decr memcache operations

### ISSUE THREAD

**Issue by m91snik** [Netflix/EVCache#21]
MemcachedClient has effective operations to increment and decrement cached values.
Is it possible to expose them through EVCacheClient as set/get/touch are done?

**Comment by lcf** [comment]
it a matter of implementing it, would it help if we submitted a pull request?

**Comment by smadappa** [comment]
Both incr and decr are now supported

https://github.com/Netflix/EVCache/blob/master/evcache-client/src/main/java/com/netflix/evcache/EVCache.java#L446

https://github.com/Netflix/EVCache/blob/master/evcache-client/src/main/java/com/netflix/evcache/EVCache.java#L459
