### ISSUE TITLE
Difference in hashing algorithm for evache-client v1.0.5 vs v4.38.0

### ISSUE THREAD

**Issue by akhitev** [Netflix/EVCache#35]
Hello,
After trying to upgrade evcache-client from v 1.0.5 to v 4.38.0 we faced found increase in cache misses during Blue-Green deployment, on  environments using more then one cache nodes.
Performing test where number of SETs performed from **old client** and GETs from **new client**, we can see that in ~50% of cases **new client** misses values. Backward test ( SETs from **new** and GETs from **old**) show almost same results.
On environments with single cache node given tests pass 100% correctly. 
Both clients using default - KETAMA hashing algorithm.

Assuming, this we think that something in hashing algorithm implementation have been changed.
Is this known issue, and are there some workaround?

**Comment by smadappa** [comment]
Hi, 

Yes, there have been changes to the hashing. For a workaround i need some more info from you

1. Are you using Eureka? If so, what is "evcache.port" value you are using to register. 
2. How are you getting the hostname? DNS?

The way we calculate the String for hashing is publicHostname/privateIp:port" (ex - ec2-174-129-159-31.compute-1.amazonaws.com/10.125.47.114:11211)

In the old client we were getting from "evcache.port". In the new one it is hardcoded to 11211

V4.38.0
result = ((InetSocketAddress)socketAddress).getHostName() + '/' + ((InetSocketAddress)socketAddress).getAddress().getHostAddress() + ":11211";

V 1.0.5
final String hostName = info.getHostName();
final String ip = info.getIPAddr();
final String port = info.getMetadata().get("evcache.port");
result = hostName + '/' + ip + ':' + ((port != null) ? port : "11211");

I suspect there might be some changes here.

**Comment by akhitev** [comment]
No we are not using eureka to discover cache servers. Port numbers are default 11211. Hosts are defined through configuration file.
We are using ZoneClusteredEVCacheClientPoolImpl

I've performed debug and it looks like difference due to different algorithms used in node locators:

in v1.0.5  used ArrayModNodeLocator actually, from spymemcached library
in v4.38.0 used EVCacheNodeLocator from EvCache (with proper Ketama algorithm)

**Comment by akhitev** [comment]
here are some details : 
ZoneClusteredEVCacheClientPoolImpl uses ZoneClusteredEVCacheClientImpl which extends AbstractEVCacheClientImpl. AbstractEVCacheClientImpl uses  BinaryConnectionFactory from spymemcached. 

AbstractEVCacheClientImpl.java:92
`
this(appName, zone, id, readTimeout,
       new BinaryConnectionFactory(maxQueueSize, DefaultConnectionFactory.DEFAULT_READ_BUFFER_SIZE, DefaultHashAlgorithm.KETAMA_HASH));
`

BinaryConnectionFactory extends DefaultConnectionFactory which instantiate ArrayModNodeLocator as NodeLocator.

DefaultConnectionFactory.java:254
`
public NodeLocator createLocator(List<MemcachedNode> nodes) {
 return new ArrayModNodeLocator(nodes, getHashAlg());
}
`


After all DefaultHashAlgorithm.KETAMA_HASH passed to ArrayModNodeLocator as hashAlg parameter. 
ArrayModNodeLocator uses following formula to get server number:


ArrayModNodeLocator.java:86
`
hashAlg.hash(key) % nodes.length
`

As we can see this algorithm does not provide consistency when number of nodes changed regardless of hashing algorithm used.

**Comment by smadappa** [comment]
Yes, there is no support for ArrayModLocator. I need to provide this support in 4.x version. 
Is this something you want to add or want us to add?

**Comment by akhitev** [comment]
No thanks, I do not think it will make sense for us to keep usage of ArrayModLocator. We'll need to migrate to 4.x version with proper consistent hashing implemented. So we can close this issue.

**Comment by smadappa** [comment]
Sounds good. Let me know if you run into any issues migrating.

**Comment by pparth** [comment]
@smadappa  Just to clarify then: we were not using a real Ketama algorithm with 1.X version of EvCache client? The Ketama algorithm has been mentioned in the wiki, even since version 1.X and we had the feeling that we were having full use of it. 
At any case, can your provide a description of what was actually supported by default with version 1.X and what is actually supported by default with version 4.X?

**Comment by smadappa** [comment]
Ketama consistent hashing algorithm is the supported in version 1.x and 4.x. The behavior is similar in both these versions
Array mod hashing was supported in version 1.x. We have not yet ported the support for ArrayMod in 4.x. If there is interest in using Mod hashing then we will port this functionality over to 4.x

**Comment by pparth** [comment]
I was asking about what is the default hashing algorithm in 1.X, Array Mod or Ketama? It seems that it is the Array Mod, whereas in the wiki documentation, only the Ketama algorithm is mentioned and this gives the impression that the Ketama is the default one in 1.X too.
Do we need to tweak any configuration in order to switch 1.X to Ketama algorithm?
