### ISSUE TITLE
NPE in EVCacheKetamaNodeLocatorConfiguration when using simple node list provider

### ISSUE THREAD

**Issue by trigan-d** [Netflix/EVCache#37]
Hi. We are facing NPE at https://github.com/Netflix/EVCache/blob/master/evcache-client/src/main/java/com/netflix/evcache/pool/EVCacheKetamaNodeLocatorConfiguration.java#L59
We have "use.simple.node.list.provider=true" and don't register our cache nodes in eureka. So DiscoveryClient.getApplication(appId) obviously returns null. 
It looks like a bug. EVCacheKetamaNodeLocatorConfiguration seems to be unaware of  SimpleNodeListProvider. Am I right?
Could you think of any possible workaround until it's fixed?

**Comment by smadappa** [comment]
Are you setting evcache.use.simple.node.list.provider=true?

Irrespective of the above property this is a bug. I will fix this asap and release a new jar.

**Comment by smadappa** [comment]
This should fix it. 
https://github.com/Netflix/EVCache/commit/d6565f2957bd8f84d2cc2999629c24dce5db49ae

evcache-client-4.71.0 has the fix for this.

**Comment by trigan-d** [comment]
> Are you setting evcache.use.simple.node.list.provider=true?
Yep, I told so. Well, ectually it's not "evcache.use.simple...", but "<CACHE_APP_NAME>.use.simple..."
Thanks for the quick fix!
