### ISSUE TITLE
SimpleNodeListProvider obtains node list from System properties instead of ConfigurationManager... again

### ISSUE THREAD

**Issue by trigan-d** [Netflix/EVCache#42]
Hi. 
Several months ago I've created an issue #28 with the same problem. My PR was approved and merged by @smadappa. 
Now I want to upgrade to EvCache 4.75.0, but see that you've reverted my fix in https://github.com/Netflix/EVCache/commit/ec41e79d1b0599d578a28901677ac177151ca906#commitcomment-21150671 (version https://github.com/Netflix/EVCache/releases/tag/v4.49.0)
What is the reason? Did it break anything? 
Thanks in advance!

**Comment by smadappa** [comment]
What we found was ConfigurationManager.getConfigInstance().getString(...) was a blocking call and all Threads would get blocked. This increased the startup times for some of our Apps. I have changed this to DynamicProperty which is also non-blocking but will use Archaius.

**Comment by smadappa** [comment]
I have released 4.76.0 with the above changes.

**Comment by trigan-d** [comment]
thanks a lot!
