### ISSUE TITLE
EVCacheNodeImpl memory leak

### ISSUE THREAD

**Issue by trigan-d** [Netflix/EVCache#43]
Hi. We are experiencing a possible memory leak in EVCacheNodeImpl.
Full GC triggered via JMX didn't allocate sufficient amount of memory. 
Initial analysis showed that major amount of memory is allocated for numerous Object[]. Links to that object are stored in multiple instances of EVCacheNodeImpl.
The problem happened twice for different EvCache-powered applications, independently. A couple of screenshots from the heap dumps attached.
EvCache version is 4.38.0
Does it say anything to you? Do you have any guess about possible reasons and workarounds?
![image-2017-03-11-15-50-12-263](https://cloud.githubusercontent.com/assets/650869/24228615/01b1d4f0-0fa8-11e7-8ed6-efc74c13e3cc.png)
![another leak of byte arrays](https://cloud.githubusercontent.com/assets/650869/24228626/0fdcc404-0fa8-11e7-9aad-f8ad869024c7.png)
![vjfds heap 1](https://cloud.githubusercontent.com/assets/650869/24228628/1240fa6c-0fa8-11e7-80b9-b5e5deaff1c6.png)

**Comment by smadappa** [comment]
I suspect you are seeing connection drop between your app and memcached. When that happens the read queue might be growing. Can you inspect the jmx console and see if any connections have dropped and read queue is growing. At times we would notice that a connection is being reported as open and active by the JVM, but while looking at netstat we would see there is no such active connections. We have added a work around to refresh such stale connections

To refresh such connections you can set the below properties
<evcache app>.EVCacheClientPool.refresh.connection.on.readQueueFull=true
<evcache app>.EVCacheClientPool.refresh.connection.on.readQueueFull.size=10

So once the queue reaches 10 it will initiate a reconnect. To use this you need to upgrade the the latest version of the jar. Hope this solves your issue.

**Comment by trigan-d** [comment]
Thanks!
What version do you mean exactly. We plan to adopt 4.76.0. Does it contain the fix?

**Comment by smadappa** [comment]
You can set these properties on 4.76.0 version. To look at all the releases check out https://github.com/Netflix/EVCache/releases
