### ISSUE TITLE
How does EVCache handle race condition caused by ReplicationAgent

### ISSUE THREAD

**Issue by zhixinwen** [Netflix/EVCache#44]
Hi,

Looks like EVCache does replication through Kafka and HTTPS. It means the replication mesaages can be out of order.
For example, SET K1=V1, DEL K1, SET K1 = V2 can be received by another datacenter as SET K1=V2, DEL, SET K1 = V1,which results into a stale value.
Does EVCache handle that? And what kind of consistency does it guarantee?

**Comment by smadappa** [comment]
The scenario that you have described is for cross region and it is best effort. It can go out of order. For cache fronting a data store we usually delete the data. i.e. if 
Region 1 we SET K1=V1 we send DEL K1 to region 2, region 3, etc. This ensure caches are coherent. 
For use cases where evcache is the data store we offer checksum in the metadata that we write to kafka. so if when K1=V1 we compute the checksum and store it. If the replication system reads value for K1 and the checksum does not match it drops the event. There might be scenarios where we read K1=V1 and within short timespan we read K1=V2. When we replicate there are chances where the other regions can have K1=V1. If strong consistency is needed you can configure the topic to do key based partitioning in kafka so the key goes to same partition and is consumed by the same consumer. This way you can synchronize cross region events. Choosing this approach however will slowdown the replication. 

For the use case where the writes happen in the same region we offer Latch which the users can block on to ensure writes are successful before they proceed to the next operation.
