### ISSUE TITLE
Large amount of PoolRefresher threads

### ISSUE THREAD

**Issue by akhitev** [Netflix/EVCache#45]
Hello,
We are using v4.76.0 with stand alone (non-eureka mode) and have two nodes memcached cluster.
We faced situation when several thousands of PoolRefresher threads remain in BLOCKED state

`    
at com.netflix.evcache.pool.EVCacheClientPool.refresh(EVCacheClientPool.java:680)
    at com.netflix.evcache.pool.EVCacheClientPool.access$200(EVCacheClientPool.java:47)
    at com.netflix.evcache.pool.EVCacheClientPool$7.run(EVCacheClientPool.java:859)
`

waiting for lock for com.netflix.evcache.pool.EVCacheClientPool owned by single PoolRefresher.
Comparing samples we can see that it's not deadlock situation and PoolRefresher which owns the lock is changing constantly. All PoolRefresher related to single memcached node.
Netstat shows that connections to this node in SYN_SENT status.
Are there workaround for this situation ?
From code I can see that it is result of EVCacheClientPool#refreshAsync. Would it make sense to limit number of concurrent refreshAsync operations?

**Comment by smadappa** [comment]
Yes, this can be unbounded. I will create a bounded thread pool to do such refresh. 
In ideal situation this should be a quick call. From the code it looks like the block is as below

https://github.com/Netflix/EVCache/blob/v4.76.0/evcache-client/src/main/java/com/netflix/evcache/pool/EVCacheClientPool.java#L680

This can happen if when there is a request to write to evcache and while processing the request we notice that we have lost a connection to a Memcached instance . The idea is to fail fast and allow reconnect asynchronously. Doing so will allow the requesting thread to proceed. Which is what it looks like but you have lots of threads blocked. 
Can you please check if some thread has held the lock and not releasing it? There might be another bug you are seeing that we have not encountered yet. I will release a new jar shortly fixing this.

**Comment by smadappa** [comment]
I have released v4.83.0. You can disable async refresh by setting the following property
<evcache app name>.disable.async.refresh=true

https://github.com/Netflix/EVCache/commit/e3e72dae87968b23b7836794b11f667e3d70e842#diff-5b0c060060e0531bc1718196e1bd348bR163

Please take a look at it and let me know if it resolved your issue. 

It will also help us if you can send your entire thread dump so that we can locate the original issue and fix it.

**Comment by akhitev** [comment]
Thanks for quick response, I'll try with new version and let you know results.

In each thread dump it is different PoolRefresher instance helding lock, and this blocking PoolRefresher is not blocked itself. So when we check situation dynamically number PoolRefresher slowly decreased. So it looks like only number of refreshes was problem.
There were some network problems on problematic memcahed node which caused large number of refreshes.

**Comment by smadappa** [comment]
I think this is due to every operation calling a refreshAsync when the node was not on the network. I will improve the refreshAsync to ensure we are not duplicating the work.
