### ISSUE TITLE
how does evcache facilitate eventual consistency?

### ISSUE THREAD

**Issue by malolk** [Netflix/EVCache#47]
Hi, 

   I found this post [Caching for a Global Netflix](https://medium.com/netflix-techblog/caching-for-a-global-netflix-7bcc457012f1) on EVCache,  but the "eventual consistency" model hadn't been elaborated in detail. 

Is there any posts or sources describing this model now?

**Comment by smadappa** [comment]
Global replication can be configured to perform invalidation or Full replication. 
1. Invalidation : A set in one region for a given key perform a delete on the other regions for the same key. When this key is requested in then other region we read it from the backing store and populate the cache. This ensures cache is coherent. 
2. Full Replication: A set in one region performs an identical operation on the other region. If the same key is written in the other region then this can result in inconsistency. If strong consistency is required then we recommend the approach described in 1.

**Comment by malolk** [comment]
Thanks! I get it.
