### ISSUE TITLE
EvCache - Eureka

### ISSUE THREAD

**Issue by mersed** [Netflix/EVCache#49]
I would like to ask question related with the EvCache and Eureka setup.
I spent quite a while checking EvCache - testing and reading about different setup's. At this moment, I am not sure what is the best implementation with Eureka.

Basically, [sample deployment](https://github.com/Netflix/EVCache/wiki/Sample-EVCache-Deployment) on wiki page explains how to run this on localhost (or on ec2 instances) with 2 replicas (with 2 shards each). But with hard coded memcached replicas/shards endpoint.

In case I want to use dynamic method of discovering servers with memcached, what I need to do in order to initialize EvCache client?

Right now, for example in Sample deployment we are creating instance of the EvCache using following:
`deploymentDescriptor = "SERVERGROUP1=localhost:11211;SERVERGROUP2=localhost:11212";
System.setProperty("EVCACHE_APP1-NODES", deploymentDescriptor);
evCache = new EVCache.Builder().setAppName("EVCACHE_APP1").build();`

In case of the Eureka, do we need to use discovery service manually and then recreate instance of evCache or this is done automatically? Is there any kind of technical wiki document which explains this setup little bit more detailed?

**Comment by mersed** [comment]
Setup i had previously almost worked prior asking this question. Additional research last 3 days resolved my issue.

**Comment by smadappa** [comment]
When using with Eureka,  EVCache Server registers it self with it. We use Prana Side car (https://github.com/Netflix/Prana) for this purpose. It basically is a light weight java process that is running along side of memcached. It's purpose is to register with eureka, collect and report stats, monitor the health of memcached, assist in taking cache warming and snapshot, etc. 

When using with Eureka there is no need to setup evcache nodes the way you have described above. They get auto discovered and polled at regular interval. This ensures if any instances crash or replaced or cluster expands or deploy new cluster the Client can auto discover and start using. This is  transparent to the clients. Whereas in the above approach if the cluster changes you have to update they system property at runtime or restart the app after setting the new properties. 

I have a few questions
1. Does your deployment use Eureka?
2. Do you use Prana or plan to use prana?
3. How do you collect and report metrics?

**Comment by mersed** [comment]
Hi @smadappa ...
Indeed, my only question was related with "They get auto discovered and polled at regular interval.".
- I completed setup of Eureka server based on the Eureka documentation
- I completed setup of EvCache server (memcached + prana) based on the wiki documentation

So everything was working, and server was properly registered on eureka side. The question was related with the EvCache client. Your answer additionally confirms my tests and findings.

---------------------------------------------------

Regarding your questions:
1. At this moment it is not using Eureka. We will go with simple deployment in order to speed up development and add eureka little bit later
2. At this moment no (but I am planing to use it for reports and stats)
3. During the dev phase I was simply checking memcached stats manually.

---------------------------------------------------

I have actually few more questions related with EvCache in general for which I was not able to find answers within documentation:
1. Currently I am initializing EvCache client using following: 
```
SERVERGROUP1=1.1.1.1:11211,2.2.2.2:11211;SERVERGROUP2=3.3.3.3:11211,4.4.4.4:11211
Where 1.1.1.1 and 2.2.2.2 bellongs to one zone
And 3.3.3.3 and 4.4.4.4 bellongs to another
```

After initialization, when I am using evCache.get("key"); checking memcached stats on both clusters (and noticing delay within the response), I can see that EvCache client is randomly getting data from both clusters. What I need to do with the current setup in order to use SERVERGROUP2 only as a fallback?

2. You mentioned above that you are using prana to assist in cache warming and snapshot? Is there any kind of documentation related with that part? Even I read about EvCache warming, I was not able to find any documentation about it.

**Comment by smadappa** [comment]
Hi @mersed 

If you are using us-east-1 region then can you please change the below property from

> SERVERGROUP1=1.1.1.1:11211,2.2.2.2:11211;SERVERGROUP2=3.3.3.3:11211,4.4.4.4:11211
Where 1.1.1.1 and 2.2.2.2 bellongs to one zone
And 3.3.3.3 and 4.4.4.4 bellongs to another
to 
> us-east-1c=1.1.1.1:11211,2.2.2.2:11211;us-east-1d=3.3.3.3:11211,4.4.4.4:11211
Where 1.1.1.1 and 2.2.2.2 bellongs to us-east-1c zone
And 3.3.3.3 and 4.4.4.4 bellongs to  us-east-1d zone

When clients in us-east-1c needs to use evcache it will use  1.1.1.1 or 2.2.2.2 based on key hashing
If you have clients in us-east-1e it will alternate between 1c and 1d zones. 

We don't use prana but we have a custom side car now called as EVCar. This in conjunction with cache warmer can be used to warmup new caches or warmup data lost due to instance replacement. These are not yet Open Sourced yet but if you are interested we can work something out. 

We also have an admin server which is very useful if you have multiple clusters of evcache to manage. 
If you are using specator (https://github.com/Netflix/spectator) then you will be able to collect and monitor metrics from evcache. 

BTW all the evcache metrics are reported via MBeans. You can look at these metrics using JMX console. They will be grouped in mbeans tab under com.netflix.evcache.

**Comment by mersed** [comment]
Hi @smadappa 

Thank you for the reply. The explanation related with alternating between zones make sense. I will try it and will let you know.

Regarding the EVCar, indeed we are really interested. Having in mind that, as part of this project we are eliminating the direct contact from the client side with the mysql database, I am really interested in solution which provides warmup of data due to the instance replacement or instance failure/restart.
As I mentioned, the initial solution will be simple, but later on we are planing to embrace EvCache fully, with multiple clusters, Eureka replicas etc ...

When do you think EvCar will be open sourced? Or how we can sort out differently?

Thank you.

**Comment by smadappa** [comment]
Hi @mersed 

Glad to hear about your project. 

evcar is checked into nflx-specific branch. (https://github.com/Netflix/EVCache/tree/nflx-specific/evcar). 
You might face issues building this as some of the jars are specific to netflix eco system and may not work in OSS. If you let me know what they are i can fix them or work with teams to see if they can be open sourced. Please update the build.gradle file and source as needed if the build fails. You can send a pull request with your changes once you get this working and i will merge them once you get working.

**Comment by mersed** [comment]
Hi @smadappa 

Thank you, I really appreciate it. I will give it a try and will let you know.

**Comment by mersed** [comment]
Hi @smadappa 

Just following up with an update as promised. Was not able to build it. It seems that few things are missing.

Additional question on top of this - during the healthcheck/ping toward eureka from evcache server (memcached + prana, or memcached + evcar) does it checkes internal memcached server automatically or it is the case which needs to be handled additionally.

Basically, my question is, if you have a process which send a health ping to eureka, what is going to happen if memcached as process goes down?

**Comment by smadappa** [comment]
Hi @mersed 

I thought so. If can tell me what exactly is failing i can see how you can circumvent that. 

For healthcheck, we write a key to memcached (heartbeat message) and read it. If these operations are successful then the evcache instance is healthy.

**Comment by mersed** [comment]
Hi @smadappa 

Sorry because of the late reply but I wanted to give it a one more try (tried to search gradle plugins which are used within the gradle build file, but was not able to find all of them). Additionally, trying to setup ecosystem using ECS which will use whole solution within our ecosystem as well (which is mostly based on node) - we decided to go with Eureka involved from the beginning.

The build fails with following errors:
-------------------------------------------------------------------------------------------------------
``Could not resolve all dependencies for configuration ':evcar:compile'.`
> Could not resolve netflix:platform:.
  Required by:
      com.netflix.evcache:evcar:4.71.0-SNAPSHOT
   > Extension of type 'RecommendationProviderContainer' does not exist. Currently registered extension types: [DefaultExtraPropertiesExtension, ReleasePluginExtension_Decorated, ReleaseExtension_Decorated, DefaultPublishingExtension_Decorated, BintrayExtension_Decorated, DependencyLockExtension_Decorated, DependencyLockCommitExtension_Decorated, ContactsExtension_Decorated, ScmInfoExtension_Decorated, ContinuousIntegrationInfoExtension_Decorated, IdeaModel_Decorated, EclipseModel_Decorated]
> Could not resolve netflix:base-server:.
  Required by:
      com.netflix.evcache:evcar:4.71.0-SNAPSHOT
   > Extension of type 'RecommendationProviderContainer' does not exist. Currently registered extension types: [DefaultExtraPropertiesExtension, ReleasePluginExtension_Decorated, ReleaseExtension_Decorated, DefaultPublishingExtension_Decorated, BintrayExtension_Decorated, DependencyLockExtension_Decorated, DependencyLockCommitExtension_Decorated, ContactsExtension_Decorated, ScmInfoExtension_Decorated, ContinuousIntegrationInfoExtension_Decorated, IdeaModel_Decorated, EclipseModel_Decorated]
> Could not resolve netflix:atlas-client:.
  Required by:
      com.netflix.evcache:evcar:4.71.0-SNAPSHOT
   > Extension of type 'RecommendationProviderContainer' does not exist. Currently registered extension types: [DefaultExtraPropertiesExtension, ReleasePluginExtension_Decorated, ReleaseExtension_Decorated, DefaultPublishingExtension_Decorated, BintrayExtension_Decorated, DependencyLockExtension_Decorated, DependencyLockCommitExtension_Decorated, ContactsExtension_Decorated, ScmInfoExtension_Decorated, ContinuousIntegrationInfoExtension_Decorated, IdeaModel_Decorated, EclipseModel_Decorated]
> Could not resolve netflix:nflibrary:.
  Required by:
      com.netflix.evcache:evcar:4.71.0-SNAPSHOT
   > Extension of type 'RecommendationProviderContainer' does not exist. Currently registered extension types: [DefaultExtraPropertiesExtension, ReleasePluginExtension_Decorated, ReleaseExtension_Decorated, DefaultPublishingExtension_Decorated, BintrayExtension_Decorated, DependencyLockExtension_Decorated, DependencyLockCommitExtension_Decorated, ContactsExtension_Decorated, ScmInfoExtension_Decorated, ContinuousIntegrationInfoExtension_Decorated, IdeaModel_Decorated, EclipseModel_Decorated]
> Could not resolve netflix:evcache-client2:.
  Required by:
      com.netflix.evcache:evcar:4.71.0-SNAPSHOT
   > Extension of type 'RecommendationProviderContainer' does not exist. Currently registered extension types: [DefaultExtraPropertiesExtension, ReleasePluginExtension_Decorated, ReleaseExtension_Decorated, DefaultPublishingExtension_Decorated, BintrayExtension_Decorated, DependencyLockExtension_Decorated, DependencyLockCommitExtension_Decorated, ContactsExtension_Decorated, ScmInfoExtension_Decorated, ContinuousIntegrationInfoExtension_Decorated, IdeaModel_Decorated, EclipseModel_Decorated]`
-------------------------------------------------------------------------------------------------------

And that is after I change the gradle build file little bit to use proper gradle plugins currently available, and to comment usage of the few which I am not able to find...
It is little bit hard to determine from my side what is wrong having in mind that mavenLocal() is used as one of the repo sources... I am not able to find some of the packages needed for gradle build...

- nebula
- netflix.ospackage-tomcat

If I comment those twos (and do not use them during the gradle build), following errors are displayed:
Publication named 'nebula' does not exist for project ':' in task ':artifactoryPublish'.
None of the specified publications matched for project ':' - nothing to publish. 

with rest of the errors copied above.

Side note question, if we setup prana now (instead of EvCar), how hard it is to switch to EvCar when (if) it become open source? Is it simple as swaping up things and setting up configuration, or it will be little bit more complex?

**Comment by mersed** [comment]
I suppose we can close this one. We went into the production without prana (or evcar) couple of weeks ago and everything works fine (nodejs in symbioses with java and EvCache and memcached with hardcoded/predefined clusters - incorporated with docker swarm mode). We will add prana as part of the next version. Thank you.
