### ISSUE TITLE
EVCache Touch method throw NoSuchMethodError exception

### ISSUE THREAD

**Issue by shengang1978** [Netflix/EVCache#56]
Here are the jar files version:
EVCache Client: 4.104
spymemcached: 2.12.3

I use the EVCache.touch(key, 120000) to refresh the time. But it throws the below exception.
java.lang.NoSuchMethodError: net.spy.memcached.OperationFactory.touch(Ljava/lang/String;ILnet/spy/memcached/ops/OperationCallback;)Lnet/spy/memcached/ops/KeyedOperation;
	net.spy.memcached.EVCacheMemcachedClient.touch(EVCacheMemcachedClient.java:322)
	com.netflix.evcache.pool.EVCacheClient.touch(EVCacheClient.java:1099)
	com.netflix.evcache.EVCacheImpl.touchData(EVCacheImpl.java:755)
	com.netflix.evcache.EVCacheImpl.touch(EVCacheImpl.java:712)
	com.netflix.evcache.EVCacheImpl.touch(EVCacheImpl.java:663)
...

Do I use the wrong jar files?

**Comment by shengang1978** [comment]
Nobody response. :(

I use the set to reset the data.

**Comment by smadappa** [comment]
We are still using spymemcached-2.11.4. Can you please try with this jar?

https://bintray.com/netflixoss/maven/EVCache/4.118.0#files/com%2Fnetflix%2Fevcache%2Fevcache-client%2F4.118.0
https://bintray.com/netflixoss/maven/download_file?file_path=com%2Fnetflix%2Fevcache%2Fevcache-client%2F4.118.0%2Fevcache-client-4.118.0.pom

**Comment by shengang1978** [comment]
I fail to download the 4.118 version. Let's wait the 5.x version.

**Comment by smadappa** [comment]
I see the jars in jcenter. We have both 4.x and 5.x here. 

http://jcenter.bintray.com/com/netflix/evcache/evcache-client/

**Comment by shengang1978** [comment]
We update to 4.127. It still throws this exception. After rollback the spymemcached to 2.11.4, it's fine.
